# Generated by Django 2.1.5 on 2019-03-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab7app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary_de',
            field=models.TextField(help_text='Enter a brief description of the book', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='summary_en',
            field=models.TextField(help_text='Enter a brief description of the book', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='summary_fr',
            field=models.TextField(help_text='Enter a brief description of the book', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
