# Generated by Django 2.1.5 on 2019-03-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab7app', '0003_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='desc_de',
            field=models.CharField(help_text='Enter a description of the page (will appear on the page)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='desc_en',
            field=models.CharField(help_text='Enter a description of the page (will appear on the page)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='desc_fr',
            field=models.CharField(help_text='Enter a description of the page (will appear on the page)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_de',
            field=models.CharField(help_text='Enter the title of the page', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(help_text='Enter the title of the page', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_fr',
            field=models.CharField(help_text='Enter the title of the page', max_length=20, null=True),
        ),
    ]
