# Generated by Django 2.1.5 on 2019-03-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab7app', '0004_auto_20190327_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image1',
            field=models.ImageField(blank=True, help_text='Upload the 1st image', null=True, upload_to='static/img/'),
        ),
        migrations.AddField(
            model_name='page',
            name='image1_de',
            field=models.ImageField(blank=True, help_text='Upload the 1st image', null=True, upload_to='static/img/'),
        ),
        migrations.AddField(
            model_name='page',
            name='image1_en',
            field=models.ImageField(blank=True, help_text='Upload the 1st image', null=True, upload_to='static/img/'),
        ),
        migrations.AddField(
            model_name='page',
            name='image1_fr',
            field=models.ImageField(blank=True, help_text='Upload the 1st image', null=True, upload_to='static/img/'),
        ),
        migrations.AddField(
            model_name='page',
            name='maincontent',
            field=models.CharField(default='null', help_text='Enter the main text that should appear on the page', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='maincontent_de',
            field=models.CharField(help_text='Enter the main text that should appear on the page', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='maincontent_en',
            field=models.CharField(help_text='Enter the main text that should appear on the page', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='maincontent_fr',
            field=models.CharField(help_text='Enter the main text that should appear on the page', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='desc',
            field=models.CharField(help_text='Enter a description of the page (will appear on the page', max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='desc_de',
            field=models.CharField(help_text='Enter a description of the page (will appear on the page', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='desc_en',
            field=models.CharField(help_text='Enter a description of the page (will appear on the page', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='desc_fr',
            field=models.CharField(help_text='Enter a description of the page (will appear on the page', max_length=100, null=True),
        ),
    ]
