# Generated by Django 2.1.5 on 2019-03-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab7app', '0005_auto_20190327_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image1',
            field=models.ImageField(blank=True, help_text='Upload the 1st image', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='image1_de',
            field=models.ImageField(blank=True, help_text='Upload the 1st image', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='image1_en',
            field=models.ImageField(blank=True, help_text='Upload the 1st image', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='image1_fr',
            field=models.ImageField(blank=True, help_text='Upload the 1st image', null=True, upload_to=''),
        ),
    ]
