# Generated by Django 2.1.5 on 2019-03-27 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab7app', '0007_auto_20190327_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='image4_de',
        ),
        migrations.RemoveField(
            model_name='page',
            name='image4_en',
        ),
        migrations.RemoveField(
            model_name='page',
            name='image4_fr',
        ),
        migrations.RemoveField(
            model_name='page',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='page',
            name='image5_de',
        ),
        migrations.RemoveField(
            model_name='page',
            name='image5_en',
        ),
        migrations.RemoveField(
            model_name='page',
            name='image5_fr',
        ),
        migrations.RemoveField(
            model_name='page',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='page',
            name='image6_de',
        ),
        migrations.RemoveField(
            model_name='page',
            name='image6_en',
        ),
        migrations.RemoveField(
            model_name='page',
            name='image6_fr',
        ),
        migrations.RemoveField(
            model_name='page',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='page',
            name='image7_de',
        ),
        migrations.RemoveField(
            model_name='page',
            name='image7_en',
        ),
        migrations.RemoveField(
            model_name='page',
            name='image7_fr',
        ),
    ]
