# Generated by Django 2.1.5 on 2019-03-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab7app', '0009_auto_20190328_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='mainimage',
            field=models.ImageField(blank=True, help_text='Upload the main image', null=True, upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='mainimage_de',
            field=models.ImageField(blank=True, help_text='Upload the main image', null=True, upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='mainimage_en',
            field=models.ImageField(blank=True, help_text='Upload the main image', null=True, upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='mainimage_fr',
            field=models.ImageField(blank=True, help_text='Upload the main image', null=True, upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='pageimages',
            name='imfile',
            field=models.ImageField(blank=True, help_text='Upload the file', null=True, upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='pageimages',
            name='imfile_de',
            field=models.ImageField(blank=True, help_text='Upload the file', null=True, upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='pageimages',
            name='imfile_en',
            field=models.ImageField(blank=True, help_text='Upload the file', null=True, upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='pageimages',
            name='imfile_fr',
            field=models.ImageField(blank=True, help_text='Upload the file', null=True, upload_to='static/img/'),
        ),
    ]
