# Generated by Django 2.1.5 on 2019-03-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab7app', '0010_auto_20190328_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageimages',
            name='page',
        ),
        migrations.AddField(
            model_name='pageimages',
            name='page',
            field=models.ForeignKey(default=1, help_text='Select a page that this image belongs to', on_delete='CASCADE', to='lab7app.Page'),
            preserve_default=False,
        ),
    ]
