# Generated by Django 2.1.5 on 2019-03-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab7app', '0011_auto_20190328_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageimages',
            old_name='page',
            new_name='pagename',
        ),
    ]
