# Generated by Django 2.1.5 on 2019-03-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab7app', '0014_auto_20190329_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(help_text='Enter the title of the page', max_length=20)),
                ('title_en', models.CharField(help_text='Enter the title of the page', max_length=20, null=True)),
                ('title_de', models.CharField(help_text='Enter the title of the page', max_length=20, null=True)),
                ('title_fr', models.CharField(help_text='Enter the title of the page', max_length=20, null=True)),
                ('desc', models.CharField(help_text='Enter a description of the page (will appear on the page', max_length=100)),
                ('desc_en', models.CharField(help_text='Enter a description of the page (will appear on the page', max_length=100, null=True)),
                ('desc_de', models.CharField(help_text='Enter a description of the page (will appear on the page', max_length=100, null=True)),
                ('desc_fr', models.CharField(help_text='Enter a description of the page (will appear on the page', max_length=100, null=True)),
                ('maincontent', models.CharField(help_text='Enter the main text that should appear on the page', max_length=300)),
                ('maincontent_en', models.CharField(help_text='Enter the main text that should appear on the page', max_length=300, null=True)),
                ('maincontent_de', models.CharField(help_text='Enter the main text that should appear on the page', max_length=300, null=True)),
                ('maincontent_fr', models.CharField(help_text='Enter the main text that should appear on the page', max_length=300, null=True)),
                ('mainimage', models.ImageField(blank=True, help_text='Upload the main image', null=True, upload_to='images/')),
                ('mainimage_en', models.ImageField(blank=True, help_text='Upload the main image', null=True, upload_to='images/')),
                ('mainimage_de', models.ImageField(blank=True, help_text='Upload the main image', null=True, upload_to='images/')),
                ('mainimage_fr', models.ImageField(blank=True, help_text='Upload the main image', null=True, upload_to='images/')),
                ('shopimage', models.ImageField(blank=True, help_text='Upload the shopping image', null=True, upload_to='images/')),
                ('shopimage_en', models.ImageField(blank=True, help_text='Upload the shopping image', null=True, upload_to='images/')),
                ('shopimage_de', models.ImageField(blank=True, help_text='Upload the shopping image', null=True, upload_to='images/')),
                ('shopimage_fr', models.ImageField(blank=True, help_text='Upload the shopping image', null=True, upload_to='images/')),
                ('drinkimage', models.ImageField(blank=True, help_text='Upload the drinking image', null=True, upload_to='images/')),
                ('drinkimage_en', models.ImageField(blank=True, help_text='Upload the drinking image', null=True, upload_to='images/')),
                ('drinkimage_de', models.ImageField(blank=True, help_text='Upload the drinking image', null=True, upload_to='images/')),
                ('drinkimage_fr', models.ImageField(blank=True, help_text='Upload the drinking image', null=True, upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='pageimages',
            name='page',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='PageImages',
        ),
    ]
